spring.application.name=backend-udecprac
spring.datasource.url=jdbc:postgresql://localhost:5432/udecprac_db
spring.datasource.username=postgres
spring.datasource.password=udecprac
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081