spring.application.name=backend-udecprac

spring.datasource.url=jdbc:postgresql://localhost:5432/estudiantes_db
spring.datasource.username=postgres
spring.datasource.password=avila12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true